#!/bin/bash
echo "Lets build!"
echo "The bootloader"
cd bootloader
./build_bootloaders
cd ..
echo "The kernel"
cd kernel
./build_kernel
cd ..
echo "The programs"
echo "The image"
echo "Copy all important files to drive ${SANDEROS_MOUNT_POINT}"
cp ./bin/* "${SANDEROS_MOUNT_POINT}/sanderos"
echo "Finished!"