#!/bin/bash
echo "Lets build!"
echo "The bootloader"
cd bootloader
./build_bootloaders
cd ..
echo "The kernel"
cd kernel
./build_kernel
cd ..
echo "The programs"
echo "The image"
guestfish --rw -a hdd.vhd -m /dev/sda:./ -f diskcmd.nsh
echo "Copy all important files to drive ${SANDEROS_MOUNT_POINT}"
cp ./bin/* "${SANDEROS_MOUNT_POINT}/sanderos"
cp ./bin/* "/media/sander/SOS/sanderos"
echo "Emulate"
qemu-system-x86_64 -drive id=disk,file=hdd.vhd,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0  -m 256m -cpu qemu64 -drive if=pflash,format=raw,unit=0,file="../OVMF.fd",readonly=on -drive if=pflash,format=raw,unit=1,file="../OVMF.fd" -net none
echo "Finished!"