#!/bin/bash
echo "Lets build!"
echo "The bootloader"
cd bootloader
./build_bootloaders || exit
cd ..
echo "The kernel"
cd kernel
./build_kernel || exit
cd ..
echo "The drivers"
cd drivers 
./build_drivers || exit
cd ..
echo "The programs"

echo "Copy all important files to drive ${SANDEROS_MOUNT_POINT}"
cp -r ./bin/* "${SANDEROS_MOUNT_POINT}"
[ -d "/media/sander/SOS" ] && cp -r ./bin/* "/media/sander/SOS"
echo "Emulate"
# guestfish --rw -a hdd.vhd -m /dev/sda1:./ -f diskcmd.nsh || exit
# qemu-system-x86_64 -drive id=disk,file=hdd.vhd,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0  -m 256m -cpu qemu64 -drive if=pflash,format=raw,unit=0,file="../OVMF.fd",readonly=on -drive if=pflash,format=raw,unit=1,file="../OVMF.fd" -net none
echo "Finished!"