// SCSI Command Name	Command Byte (OpCode)
// TEST UNIT READY	0x00
#define SCSI_TEST_UNIT_READY 0x00
// REQUEST SENSE	0x03
#define SCSI_REQUEST_SENSE 0x03
// FORMAT UNIT	0x04
#define SCSI_FORMAT_UNIT  0x04
// INQUIRY	0x12
#define SCSI_INQUIRY 0x12
// START STOP UNIT (Eject device)	0x1B
#define SCSI_START_STOP_UNIT_EJECT 0x1B
// PREVENT ALLOW MEDIUM REMOVAL	0x1E
#define SCSI_PREVENT_ALLOW_MEDIUM_REMOVAL 0x1E
// READ FORMAT CAPACITIES	0x23
#define SCSI_READ_FORMAT_CAPABILITIES 0x23
// READ CAPACITY	0x25
#define SCSI_READ_CAPACITY 0x25
// READ (10)	0x28
#define SCSI_READ_10 0x28
// WRITE (10)	0x2A
#define SCSI_WRITE_10 0x2A
// SEEK (10)	0x2B
#define SCSI_SEEL_10 0x2B
// WRITE AND VERIFY (10)	0x2E
#define SCSI_WRITE_AND_VERIFY_10 0x2E
// VERIFY (10)	0x2F
#define SCSI_VERIFY_10
// SYNCHRONIZE CACHE	0x35
#define SCSI_SYNCHRONIZE_CACHE 0x35
// WRITE BUFFER	0x3B
#define SCSI_WRITE_BUFFER 0x3B
// READ BUFFER	0x3C
#define SCSI_READ_BUFFER 0x3C
// READ TOC/PMA/ATIP	0x43
#define SCSI_READ_TOC_PMA_ATIP 0x43
// GET CONFIGURATION	0x46
#define SCSI_GET_CONFIGURATION 0x46
// GET EVENT STATUS NOTIFICATION	0x4A
#define SCSI_GET_EVENT_STATUS_NOTIFICATION 0x4A
// READ DISC INFORMATION	0x51
#define SCSI_READ_DISC_INFORMATION 0x51
// READ TRACK INFORMATION	0x52
#define SCSI_READ_TRACK_INFORMATION 0x52
// RESERVE TRACK	0x53
#define SCSI_RESERVE_TRACK 0x53
// SEND OPC INFORMATION	0x54
#define SCSI_SEND_OPC_INFORMATION 0x54
// MODE SELECT (10)	0x55
#define SCSI_MODE_SELECT_10 0x55
// REPAIR TRACK	0x58
#define SCSI_REPAIR_TRACK 0x58
// MODE SENSE (10)	0x5A
#define SCSI_MODE_SENSE_10 0x5A
// CLOSE TRACK SESSION	0x5B
#define SCSI_CLOSE_TRACK_SESSION 0x5B
// READ BUFFER CAPACITY	0x5C
#define SCSI_READ_BUFFER_CAPACITY 0x5C
// SEND CUE SHEET	0x5D
#define SCSI_SEND_CUE_SHEET 0x5D
// REPORT LUNS	0xA0
#define SCSI_REPORT_LUNS 0xA0
// BLANK	0xA1
#define SCSI_BLANK 0xA1
// SECURITY PROTOCOL IN	0xA2
#define SCSI_SECURITY_PROTOCOL_IN 0xA2
// SEND KEY	0xA3
#define SCSI_SEND_KEY 0xA3
// REPORT KEY	0xA4
#define SCSI_REPORT_KEY 0xA4
// LOAD/UNLOAD MEDIUM	0xA6
#define SCSI_LOAD_UNLOAD_MEDIUM 0xA6
// SET READ AHEAD	0xA7
#define SCSI_SET_READ_AHEAD 0xA7
// READ (12)	0xA8
#define SCSI_READ_12 0xA8
// WRITE (12)	0xAA
#define SCSI_WRITE_12 0xAA
// READ MEDIA SERIAL NUMBER / SERVICE ACTION IN (12)	0xAB / 0x01
#define SCSI_READ_MEDIA_SERIAL_NUMBER 0xAB
// GET PERFORMANCE	0xAC
#define SCSI_GET_PERFORMANCE 0xAC
// READ DISC STRUCTURE	0xAD
#define SCSI_READ_DISC_STRUCTURE 0xAD
// SECURITY PROTOCOL OUT	0xB5
#define SCSI_SECURITY_PROTOCOL_OUT 0xB5
// SET STREAMING	0xB6
#define SCSI_SET_STREAMING 0xB6
// READ CD MSF	0xB9
#define SCSI_READ_CD_MSF 0xB9
// SET CD SPEED	0xBB
#define SCSI_SET_CD_SPEED 0xBB
// MECHANISM STATUS	0xBD
#define SCSI_MECHANISM_STATUS 0xBD
// READ CD	0xBE
#define SCSI_READ_CD 0xBE
// SEND DISC STRUCTURE	0xBF
#define SCSI_SEND_DISC_STRUCTURE 0xBF