#!/bin/bash
nasm -felf64 startup.asm -o startup.o
$SANDEROS_CROSS_LOCATION/x86_64-elf-gcc -I "../../programsapi/include" -ffreestanding -fno-PIE -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -c ./main.c -o ./cht.o -D __SANDEROSUSB -D trylocal
$SANDEROS_CROSS_LOCATION/x86_64-elf-gcc -ffreestanding -nostdlib -lgcc -T ../../programsapi/linker.ld -fno-PIE ./startup.o ../../programsapi/stdlib.o ./cht.o -o ./chat.bin
rm *.o
cp ./chat.bin ../../bin/programs/chat.bin